version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  socialmedia-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socialmedia-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/socialmedia
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
